### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by haumenphai** [haumenphai/document-app#17]
- [ ] thêm menu insert demo model
- [ ] Thêm date field type
- [ ] Khi delete hay edit record thì index record bị đánh về 1
- [ ] Sau khi hủy tìm kiếm thì thứ tự recors ko còn được như cũ
- [x] Edit nhập giá trị cho record có vấn đề
- [x] Định dạng ngày đang format là 12h mà ko có AM, PM => chuyển về 24h
- [x] Mũi tên sort không hiển thị lần đầu trong table view
- [x] Chỉnh sửa lần cuối trong table view không hiển thị đúng dạng
- [x] Button hủy không close được dialog khi edit model
- [x] Button hủy không close được dialog khi xoá model
