### ISSUE TITLE
Todo list [Style]

### ISSUE THREAD

**Issue by haumenphai** [haumenphai/document-app#19]
- [x] Thay đổi màu nền ModelActivity thành trắng để cùng màu với item model
- [x] Thêm title cho dialog pick icon 
- [ ] Thêm icon app
- [ ] Thêm và chỉnh sửa bộ icon model
- [x] Khi edit model name thì vùng thêm vùng chọn all text thay vì để con trỏ ở cuối
- [x] Căn giữa model icon và model name
- [ ] Chỉnh sửa màu nền item add new model để phân biệt với model
- [ ]  theme app
